### PR TITLE
Update mediawiki

### PR DESCRIPTION
**Pull request by LegoFan4000**

### CODE REVIEW

**Comment by Reception123** [comment]
@Legofan4000 Not sure about this. How was it done, did you use git command line or did you just click on something on Github?

**Comment by LegoFan4000** [comment]
I clicked around in github

**Comment by Reception123** [comment]
@LegoFan4000 OK. Everything seems good to me but I will wait for a more experienced sysadmin for the merge, as it is not urgent and I don't want anything to go wrong.

**Comment by LegoFan4000** [comment]
Any updates on this?

**Comment by Southparkfan** [comment]
I am not sure how you generated this pull request.

Please let me look tomorrow before I decline/accept.

**Comment by LegoFan4000** [comment]
I did this by clicking around in GitHub.

**Comment by JohnFLewis** [comment]
This updates to an unreleased version (1.27.2)

**Pull request closed without merging**
