### PR TITLE
Update DarkMode

### PR DESCRIPTION
**Pull request by R4356th**
DarkMode had some important changes upstream and it being a global extension should justify updating right away instead of waiting for 1.36.

### CODE REVIEW

**Comment by Universal-Omega** [comment]
Looking at changes in compare view it doesnt look like anything was changed, are you sure it was changed on the correct branch?

**Comment by R4356th** [comment]
> 
> 
> Looking at changes in compare view it doesnt look like anything was changed, are you sure it was changed on the correct branch?

Git just happened to make an extra commit after I ran ``git pull origin master``. I am currently recloning this repository to fix this.

**Comment by Universal-Omega** [comment]
> > Looking at changes in compare view it doesnt look like anything was changed, are you sure it was changed on the correct branch?
> 
> Git just happened to make an extra commit after I ran `git pull origin master`. I am currently recloning this repository to fix this.

The last update on our branch of the extension was December 31.

**Comment by R4356th** [comment]
I will see if I can get the patch backported.

**Comment by Universal-Omega** [comment]
> I did not notice we were using REL1_35. I will see if I can get the patch backported.

It needs backported to REL1_36 also by the way.

**Pull request closed without merging**
