### PR TITLE
Change branch from master to main for Citizen

### PR DESCRIPTION
**Pull request by alistair3149**
Citizen has changed its default branch from master to main.

### CODE REVIEW

**Comment by Universal-Omega** [comment]
Was this done using git? Doing this without git with mess up submodules I think.

**Comment by alistair3149** [comment]
> Was this done using git? Doing this without git with mess up submodules I think.

No, would you like me to do a submodule sync and update for the PR?
The old master branch would continue to redirect and point to the main branch so functionally it is still the same.

**Comment by Universal-Omega** [comment]
> > Was this done using git? Doing this without git with mess up submodules I think.
> 
> No, would you like me to do a submodule sync and update for the PR?
> The old master branch would continue to redirect and point to the main branch so functionally it is still the same.

Yes if you would do the submodule sync and update it would be great, but it is also not a requirement to even do this right now, because it is redirected, so not a priority. Thanks!

**Comment by alistair3149** [comment]
> > > Was this done using git? Doing this without git with mess up submodules I think.
> > 
> > 
> > No, would you like me to do a submodule sync and update for the PR?
> > The old master branch would continue to redirect and point to the main branch so functionally it is still the same.
> 
> Yes if you would do the submodule sync and update it would be great, but it is also not a requirement to even do this right now, because it is redirected, so not a priority. Thanks!

I update the submodule but I think sync needed to be done on wherever is pulling the repo, but it really doesn't matter since it is essentially the same branch but just a name change. I also update it on the REL1_35 PR. Either way I noticed the skin is in an older version so it might be nice to update it.

**Comment by Universal-Omega** [comment]
Did this with #1924

**Pull request closed without merging**
