### PR TITLE
Add DeleteUserPages extension (T6139)

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Review by RhinosF1 — COMMENTED** [review]
Not sure all are you but why is ignore = dirty missing from some

**Comment by Universal-Omega** [comment]
> Not sure all are you but why is ignore = dirty missing from some

Yeah, was wondering that as well, but I just decided to follow the more recent extensions, and not edit to add that.

**Comment by Reception123** [comment]
That would be my fault, as I honestly don't know how you're supposed to get the = dirty part, do you just edit manually?

**Comment by Universal-Omega** [comment]
> That would be my fault, as I honestly don't know how you're supposed to get the = dirty part, do you just edit manually?

Yeah, you just edit manually to add that. Would you like me to do a new PR adding those?

**Pull request merged**
