### PR TITLE
Add MultiUpload extension

### PR DESCRIPTION
**Pull request by Reception123**
It worked!! I actually did it! (I guess there will be some mistakes..)

### CODE REVIEW

**Comment by Reception123** [comment]
@JohnFLewis @Southparkfan Probably still did some mistakes but at least I managed to use command line..

**Comment by Southparkfan** [comment]
You almost did it indeed, but the extension/submodule is now stored in a directory called git...

git submodule add -f -b REL1_25 https://github.com/wikimedia/mediawiki-extensions-MultiUpload extensions/MultiUpload

The last argument (extensions/MultiUpload) tells git where the submodule should be stored. In this case this command needs to be ran from the very root directory (where normally LocalSetting.php is stored).

Fixing this PR is an annoying process that is even for me very complicated, so I'll close this PR for now.

**Comment by Reception123** [comment]
Oh ok.

**Comment by Reception123** [comment]
@Southparkfan How do I make a separate PR from command line? (I tried but it got into the same one)

**Comment by Southparkfan** [comment]
Well first you make sure your master branch (the one of your mediawiki fork) is synced with Miraheze's one, then you need to create a branch in your mediawiki fork. You run the git commands in that branch, you push the new changes to GitHub and then you create a pull request for that branch.

Let me know if you need help; I agree this is difficult with GitHub.

**Pull request closed without merging**
