### PR TITLE
T10794: Add Extension:OOJSPlus

### PR DESCRIPTION
**Pull request by brandon-wm**

### CODE REVIEW

**Comment by AgentIsai** [comment]
And for REL1_40?

**Comment by brandon-wm** [comment]
Ah yes, I forgot about that branch. @AgentIsai, will I need to do the entire process for REL1_40 as well?

**Review by Reception123 — APPROVED** [review]

**Comment by Reception123** [comment]
> Ah yes, I forgot about that branch. @AgentIsai, will I need to do the entire process for REL1_40 as well?

The mediawiki one yes.

**Comment by Reception123** [comment]
Since @brandon-wm said they had issues with REL1_40 I've done that myself since this is a high priority task.

**Pull request merged**
