### PR TITLE
Switch to 'stable' branch for SnapProjectEmbed 

### PR DESCRIPTION
**Pull request by R4356th**
``master`` will be used for changes not yet ready to be released from now on and ``stable`` will be updated once a new version is ready. 

(I am an upstream maintainer.)

### CODE REVIEW

**Comment by RhinosF1** [comment]
Please also do 1.36 branch

**Comment by R4356th** [comment]
> 
> 
> Please also do 1.36 branch

Sorry for the delay. Done in #1606.

**Comment by Universal-Omega** [comment]
Conflict.

**Comment by Universal-Omega** [comment]
Closing since we can't really test 1.35 changes anymore, and the extension will likely not be updated again until 1.36 is deployed anyways, in addition to the merge conflict.

**Pull request closed without merging**
